// <auto-generated />
using BascketApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BascketApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BascketAppDbContext))]
    [Migration("20220913210248_InitialMigartion")]
    partial class InitialMigartion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BascketApp.Domain.Entities.Bascket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PaysVAT")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Basckets");
                });

            modelBuilder.Entity("BascketApp.Domain.Entities.BascketArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BascketId")
                        .HasColumnType("integer");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BascketId");

                    b.ToTable("BascketArticles");
                });

            modelBuilder.Entity("BascketApp.Domain.Entities.BascketArticle", b =>
                {
                    b.HasOne("BascketApp.Domain.Entities.Bascket", "Bascket")
                        .WithMany("Articles")
                        .HasForeignKey("BascketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bascket");
                });

            modelBuilder.Entity("BascketApp.Domain.Entities.Bascket", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
